# PostgreSQL Database Configuration for COINS Project

# App
server.port=8080

spring.datasource.url=jdbc:postgresql://big_postgres:5432/bigdb
spring.datasource.username=biguser
spring.datasource.password=bigpass

# PostgreSQL driver
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate - 'none' because tables already exist
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# Optional: Add this if you want to see more detailed logs
logging.level.edu.SIUE=DEBUG

management.endpoints.web.exposure.include=health
management.endpoint.health.probes.enabled=true